version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: liquibase-postgres
    environment:
      POSTGRES_DB: liquibase_demo
      POSTGRES_USER: liquibase_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  liquibase:
    image: maven:3.8-openjdk-17
    container_name: liquibase-runner
    volumes:
      - ../liquibase:/app
    working_dir: /app
    depends_on:
      - postgres
    command: >
      /bin/bash -c "
      sleep 5 &&
      mvn liquibase:update -Dliquibase.propertyFile=src/main/resources/liquibase-docker.properties
      "

volumes:
  postgres_data: