version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: liquibase-postgres
    environment:
      POSTGRES_DB: liquibase_demo
      POSTGRES_USER: liquibase_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: