name: Liquibase Database Migration - Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'src/main/resources/db/changelog/**'
  workflow_dispatch:

jobs:
  liquibase-staging:
    name: Run Liquibase on Staging
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Create Liquibase properties file
        run: |
          cat > src/main/resources/liquibase-staging.properties << EOF
          changeLogFile=db/changelog/db.changelog-master.yaml
          url=${{ secrets.STAGING_DB_URL }}
          username=${{ secrets.STAGING_DB_USERNAME }}
          password=${{ secrets.STAGING_DB_PASSWORD }}
          driver=org.postgresql.Driver
          EOF
          
      - name: Generate Update SQL Script
        run: |
          mvn liquibase:updateSQL \
            -Dliquibase.propertyFile=src/main/resources/liquibase-staging.properties
            
      - name: Run Liquibase Update
        run: |
          mvn liquibase:update \
            -Dliquibase.propertyFile=src/main/resources/liquibase-staging.properties