name: Liquibase Database Migration - Development

on:
  push:
    branches:
      - develop
    paths:
      - 'src/main/resources/db/changelog/**'
  workflow_dispatch:

jobs:
  liquibase-dev:
    name: Run Liquibase on Development
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Create Liquibase properties file
        run: |
          cat > src/main/resources/liquibase-dev.properties << EOF
          changeLogFile=db/changelog/db.changelog-master.yaml
          url=${{ secrets.DEV_DB_URL }}
          username=${{ secrets.DEV_DB_USERNAME }}
          password=${{ secrets.DEV_DB_PASSWORD }}
          driver=org.postgresql.Driver
          EOF
          
      - name: Run Liquibase Update
        run: |
          mvn liquibase:update \
            -Dliquibase.propertyFile=src/main/resources/liquibase-dev.properties