name: Liquibase Database Migration - Production

on:
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Confirmar despliegue a producción (yes/no)'
        required: true
        default: 'no'

jobs:
  liquibase-prod:
    name: Run Liquibase on Production
    runs-on: ubuntu-latest
    environment: production
    if: github.event.inputs.confirm_deployment == 'yes'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Create Liquibase properties file
        run: |
          cd liquibase
          cat > src/main/resources/liquibase-prod.properties << EOF
          changeLogFile=db/changelog/db.changelog-master.yaml
          url=${{ secrets.PROD_DB_URL }}
          username=${{ secrets.PROD_DB_USERNAME }}
          password=${{ secrets.PROD_DB_PASSWORD }}
          driver=org.postgresql.Driver
          EOF
          
      - name: Generate Update SQL Script
        run: |
          cd liquibase
          mvn liquibase:updateSQL \
            -Dliquibase.propertyFile=src/main/resources/liquibase-prod.properties
            
      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          issue-title: "Aprobar migración de base de datos a Producción"
          issue-body: "Por favor revisa el script SQL generado y aprueba la migración a producción."
          
      - name: Run Liquibase Update
        run: |
          cd liquibase
          mvn liquibase:update \
            -Dliquibase.propertyFile=src/main/resources/liquibase-prod.properties